### ISSUE TITLE
パスワードに記号が入っていたらログインできない

### ISSUE THREAD

**Issue by southrop** [himananiito/livedl#18]
ランダム生成のパスワードを使っていましたが `-nico-login` で使うと `login failed: session_key not found` のエラーが帰ってくる。数回失敗したらアカウントがロックされてしまい、サイトからアンロックとパスワード変更しないと行けなかった。今回は記号なしのパスワードを試したら一発おｋでした。

ちなみに前のパスワードは `9l$KZQdrs%eZNOLN` でした。

**Comment by himananiito** [comment]
お手数かけてしまい申し訳ありません。
-nico-loginでパスワードに$が入っていると、Powershellでは（shやbash等でも）
変数と認識されるため、livedlに渡される前に文字列が変化してしまいます。
Powershell(やbash)の場合は、必ずシングルクォートで囲ってください。

`-nico-login 'test@test.com,9l$KZQdrs%eZNOLN'`

```
> echo "9l$KZQdrs%eZNOLN"
9l%eZNOLN
> echo '9l$KZQdrs%eZNOLN'
9l$KZQdrs%eZNOLN
```

**Comment by southrop** [comment]
そういう事でしたのか！失礼しました！
