### ISSUE TITLE
[ニコ生] 会場時刻からでなく開演時刻から録画したい

### ISSUE THREAD

**Issue by himananiito** [himananiito/livedl#25]
ツイッターからの要望。
たまにその番組の開演時刻の前に関連するCMが流れるらしいので、マージンを指定できるようにするなど検討する。

**Comment by himananiito** [comment]
情報提供ありがとうございます！今度確認してみます。

**Comment by arigayas** [comment]
> -nico-ts-start <num>           タイムシフトの録画を指定した再生時間(秒)から開始する

で公式放送の開演時刻から録画出来るようになりましたが、
公式の「アニメの一挙(*)」だと開演時刻の10分前の作品と30分前の作品があるので
「何分」で指定できると計算する手間が減ってありがたいです。

例えば「 -nico-ts-start-min  <num> 」というオプションを新設するのはいかがでしょうか？

開演時刻の10分前の作品：http://live.nicovideo.jp/gate/lv316620164
開演時刻の30分前の作品：http://live.nicovideo.jp/gate/lv316601033

(*)：ニコニコアニメスペシャル - ニコ百 https://dic.nicovideo.jp/id/4564966

**Comment by himananiito** [comment]
sarami55さん、オプション追加ありがとうございます。マージしました。

**Comment by arigayas** [comment]
sarami55さん、オプション追加ありがとうございます。

> 開場時刻(opentime)と開始時刻(begin time)がありますが、
> いまのオプション処理ではopentimeからの偏差になっています。
> opentime がbegin time より10分早いと 30分スタートを遅らせても
> 保存されるのは期待していた時刻より10分前になってしまうようです。
> 
> 大抵は開場と開始が同時刻になっているんじゃないかな。

なるほど。

メモとしてですが、[けものフレンズの一挙](http://live.nicovideo.jp/gate/lv295700989)の時は
開場時刻(opentime)が開始時刻(begin time)の60分前だったので、
まれに開場時刻が開始時刻の60分前という番組があるということをコメントしておきます。
