### ISSUE TITLE
Is it not working now?

### ISSUE THREAD

**Issue by Kotsuha** [himananiito/livedl#45]
Hello.

I have successfully used livedl to download from Niconico Timeshift before. But today when I try to use it

```
D:\Users\user\Downloads\livedl-2alpha\livedl-2alpha
λ livedl.exe -nico-login "見せられないよ,見せられないよ" lv見せられないよ
niconico account saved.
Conf(NicoLoginOnly): false
Conf(NicoFormat): ""
Conf(NicoLimitBw): 0
Conf(NicoHlsOnly): false
Conf(NicoRtmpOnly): false
Conf(NicoFastTs): false
Conf(NicoAutoConvert): false
Conf(NicoForceResv): false
Conf(NicoSkipHb): false
Conf(HttpSkipVerify): false
chdir: D:\Users\user\Downloads\livedl-2alpha\livedl-2alpha
```

It just hangs there. The download never starts. Just want to ask that is it not working now or am I missing something? Thank you.

**Comment by skillgod** [comment]
yeh,me too. I guess niconico is blocking the connection

**Comment by nnn-revo2012** [comment]
Hello.

Niconico timeshift  must  -nico-login-only=on  option .

**Comment by nnn-revo2012** [comment]
Hello.
Be sure to add -nico-login-only=on option when recording Niconico Timeshift or Channel limited broadcasts.
Because the specifications of Niconico server changed on December 5, 2019.

If you can read Japanese, see below.
日本語が読めるなら以下を見てください。
https://himananiito.hatenablog.jp/entry/livedl#%E6%9C%AC%E3%83%84%E3%83%BC%E3%83%AB%E3%81%AB%E9%96%A2%E3%81%99%E3%82%8B%E3%82%B3%E3%83%A1%E3%83%B3%E3%83%88

**Comment by skillgod** [comment]
> Hello.
> Be sure to add -nico-login-only=on option when recording Niconico Timeshift or Channel limited broadcasts.
> Because the specifications of Niconico server changed on December 5, 2019.
> 
> If you can read Japanese, see below.
> 日本語が読めるなら以下を見てください。
> https://himananiito.hatenablog.jp/entry/livedl#%E6%9C%AC%E3%83%84%E3%83%BC%E3%83%AB%E3%81%AB%E9%96%A2%E3%81%99%E3%82%8B%E3%82%B3%E3%83%A1%E3%83%B3%E3%83%88

Thanks! it works!

**Comment by Kotsuha** [comment]
> 
> 
> Hello.
> Be sure to add -nico-login-only=on option when recording Niconico Timeshift or Channel limited broadcasts.
> Because the specifications of Niconico server changed on December 5, 2019.
> 
> If you can read Japanese, see below.
> 日本語が読めるなら以下を見てください。
> https://himananiito.hatenablog.jp/entry/livedl#%E6%9C%AC%E3%83%84%E3%83%BC%E3%83%AB%E3%81%AB%E9%96%A2%E3%81%99%E3%82%8B%E3%82%B3%E3%83%A1%E3%83%B3%E3%83%88

Life is wonderful now. Thank you so much!

**Comment by Kotsuha** [comment]
> If you can read Japanese, see below.
> 日本語が読めるなら以下を見てください。
> https://himananiito.hatenablog.jp/entry/livedl#%E6%9C%AC%E3%83%84%E3%83%BC%E3%83%AB%E3%81%AB%E9%96%A2%E3%81%99%E3%82%8B%E3%82%B3%E3%83%A1%E3%83%B3%E3%83%88

Just another link which may be more directly
https://himananiito.hatenablog.jp/entry/livedl#comment-26006613486277096
