### ISSUE TITLE
I can not download videos from timeshift

### ISSUE THREAD

**Issue by railannad** [himananiito/livedl#49]
Hello, this program is very convenient and it helps me much. But today it does not work, here are information, thanks in advance.

COMMAND:  livedl/livedl -nico-login-only=on -nico-fast-ts -nico-login "mymail,mypassword" -nico-format xxx -nico lvxxxxxxxxxx
OUTPUT:
niconico account saved.
Conf(NicoLoginOnly): true
Conf(NicoFormat): "xxx"
Conf(NicoLimitBw): 0
Conf(NicoHlsOnly): false
Conf(NicoRtmpOnly): false
Conf(NicoFastTs): true
Conf(NicoAutoConvert): false
Conf(NicoForceResv): true
Conf(NicoSkipHb): false
Conf(HttpSkipVerify): false
chdir: /root/livedl
2020/06/05 03:08:12 Unknown error: map[string]interface {}{"data":map[string]interface {}{"code":"INVALID_MESSAGE"}, "type":"error"}

**Comment by railannad** [comment]
It worked successfully on 2 Jun, but today it does not work

**Comment by panam510** [comment]
Hello.

Since niconico has upgraded their private API, livedl is no longer working properly.
A patch for this problem has been released on the 5ch forum by volunteers. Give it a try.

Patch:
http://egg.5ch.net/test/read.cgi/software/1570634489/535
https://thuploader.orz.hm/uploader/?mode=dl&id=19571

Windows x86 binary (but the fast-ts option is disabled, I haven't tried this):
http://egg.5ch.net/test/read.cgi/software/1570634489/581
https://www.axfc.net/u/4023027

**Comment by railannad** [comment]
> Hello.
> 
> Since niconico has upgraded their private API, livedl is no longer working properly.
> A patch for this problem has been released on the 5ch forum by volunteers. Give it a try.
> 
> Patch:
> http://egg.5ch.net/test/read.cgi/software/1570634489/535
> https://thuploader.orz.hm/uploader/?mode=dl&id=19571
> 
> Windows x86 binary (but the fast-ts option is disabled, I haven't tried this):
> http://egg.5ch.net/test/read.cgi/software/1570634489/581
> https://www.axfc.net/u/4023027

Thanks, and would you tell me how to use it?  I copied it to "/livedl" and it still did not work
![image](https://user-images.githubusercontent.com/36919867/83835707-128b4600-a724-11ea-90a4-a450ad15c4ed.png)

**Comment by panam510** [comment]
You need to install golang, gcc, git and build livedl from the source code. Instructions can be found at Readme.md.
https://github.com/himananiito/livedl

Open the console and run the lines from 
`wget https://dl.google.com/go/go1.10.3.linux-amd64.tar.gz`
to
`cd livedl`
Run all 12 lines (if you have golang, gcc, or git installed, you can skip those lines).

Once that's done, patch it up. The source code will be in a state to support the new version of the API.
`patch < livedl.patch`

If the patch succeeds, build it.
`go build src/livedl.go`
If the livedl executable has been updated to a new date, the build is successful.

**Comment by railannad** [comment]
> You need to install golang, gcc, git and build livedl from the source code. Instructions can be found at Readme.md.
> https://github.com/himananiito/livedl
> 
> Open the console and run the lines from
> `wget https://dl.google.com/go/go1.10.3.linux-amd64.tar.gz`
> to
> `cd livedl`
> Run all 12 lines (if you have golang, gcc, or git installed, you can skip those lines).
> 
> Once that's done, patch it up. The source code will be in a state to support the new version of the API.
> `patch < livedl.patch`
> 
> If the patch succeeds, build it.
> `go build src/livedl.go`
> If the livedl executable has been updated to a new date, the build is successful.
I tried but failed , I hope he can share his "nico_hls.go" instead "livedl.patch", it's too hard for me
COMMAND: patch < livedl.patch
OUTPUT:
can't find file to patch at input line 3
Perhaps you should have used the -p or --strip option?
The text leading up to this was:
--------------------------
|--- src/niconico/nico_hls.go.old	2020-04-30 23:08:42.843431952 +0900
|+++ src/niconico/nico_hls.go	2020-06-03 06:42:56.848093786 +0900
--------------------------
File to patch:

**Comment by railannad** [comment]
> You need to install golang, gcc, git and build livedl from the source code. Instructions can be found at Readme.md.
> https://github.com/himananiito/livedl
> 
> Open the console and run the lines from
> `wget https://dl.google.com/go/go1.10.3.linux-amd64.tar.gz`
> to
> `cd livedl`
> Run all 12 lines (if you have golang, gcc, or git installed, you can skip those lines).
> 
> Once that's done, patch it up. The source code will be in a state to support the new version of the API.
> `patch < livedl.patch`
> 
> If the patch succeeds, build it.
> `go build src/livedl.go`
> If the livedl executable has been updated to a new date, the build is successful.

It worked successfully.  Thank you againly
I searched the principle of patch format file ,then I used `CTRL+F` and replaced them one by one

**Comment by panam510** [comment]
I'm glad it worked.

Sorry, I was missing an option for the patch command.
There are two ways to do this.

Method A)
Add the -p0 option to patch.
`patch -p0 < livedl.patch`

Method B)
Move livedl.patch to the same directory as nico_hls.go, and then patch it.
`mv livedl.patch src/niconico/`
`cd src/niconico/`
`patch < livedl.patch`

For more information, see patch's manpage.
`man patch`

**Comment by railannad** [comment]
> I'm glad it worked.
> 
> Sorry, I was missing an option for the patch command.
> There are two ways to do this.
> 
> Method A)
> Add the -p0 option to patch.
> `patch -p0 < livedl.patch`
> 
> Method B)
> Move livedl.patch to the same directory as nico_hls.go, and then patch it.
> `mv livedl.patch src/niconico/`
> `cd src/niconico/`
> `patch < livedl.patch`
> 
> For more information, see patch's manpage.
> `man patch`

I tried "Method B)" on another VPS , then ....
![image](https://user-images.githubusercontent.com/36919867/83855592-e20ad280-a74a-11ea-86af-ce24f82b6430.png)

**Comment by panam510** [comment]
You need to fix the line endings because it says "different line endings".

Open nico_hls.go with a text editor, change the line endings from "CR+LF" to "LF" and overwrite the file.
If you don't have a suitable text editor, you can use the dos2unix command.
`dos2unix nico_hls.go`
Then patch it.

I'm sure there are more fundamental ways to fix it (such as changing the git configuration), but I think this should work for now.

A similar example:
https://unix.stackexchange.com/questions/239364/how-to-fix-hunk-1-failed-at-1-different-line-endings-message

**Comment by railannad** [comment]
> You need to fix the line endings because it says "different line endings".
> 
> Open nico_hls.go with a text editor, change the line endings from "CR+LF" to "LF" and overwrite the file.
> If you don't have a suitable text editor, you can use the dos2unix command.
> `dos2unix nico_hls.go`
> Then patch it.
> 
> I'm sure there are more fundamental ways to fix it (such as changing the git configuration), but I think this should work for now.
> 
> A similar example:
> https://unix.stackexchange.com/questions/239364/how-to-fix-hunk-1-failed-at-1-different-line-endings-message

Thank you ,  successed after "dos2unix nico_hls.go" 
![image](https://user-images.githubusercontent.com/36919867/83859897-27ca9980-a751-11ea-9506-476f78237106.png)

**Comment by mishina2228** [comment]
> A patch for this problem has been released on the 5ch forum by volunteers. 

Hopefully the person who created this patch will send out a pull request!
