### ISSUE TITLE
ログイン後のINVALID_MESSAGEメッセージについて

### ISSUE THREAD

**Issue by sangwon-jung-work** [himananiito/livedl#50]
ニコ生タイムシフト録画中に下記のようなエラーが発生しました。
(Docker使いました)

(略) livedl --no-chdir -nico-login "(ID),(PW)" -nico-auto-convert=on -nico-login-only=on (nicolive-ID)

niconico account saved.
Conf(NicoLoginOnly): true
Conf(NicoFormat): ""
Conf(NicoLimitBw): 0
Conf(NicoHlsOnly): false
Conf(NicoRtmpOnly): false
Conf(NicoFastTs): false
Conf(NicoAutoConvert): true
Conf(NicoAutoDeleteDBMode): 0
Conf(ExtractChunks): false
Conf(ConvExt): ""
Conf(NicoForceResv): false
Conf(NicoSkipHb): false
Conf(HttpSkipVerify): false
not_login
login success
2020/06/07 07:27:23 Unknown error: map[string]interface {}{"type":"error", "data":map[string]interface {}{"code":"INVALID_MESSAGE"}}

nico.goのログインAPIにPOSTリクエストを送ってみたら、cookieでセッションキーが出てきました（bodyはなし）
何かの代替や方法があるでしょうか？

**Comment by nek010n** [comment]
#49 を見てみて、APIが変更になった。

**Comment by sangwon-jung-work** [comment]
closed issueを逃していました；
ありがとうございます。
