### ISSUE TITLE
Cannot download channel member only timeshifted videos

### ISSUE THREAD

**Issue by Kennnnnnji** [himananiito/livedl#52]
`./livedl -nico -nico-login "xxx,xxx" -nico-login-only=on lvxxx`
Given this error:
```
niconico account saved.
Conf(NicoLoginOnly): true
Conf(NicoFormat): ""
Conf(NicoLimitBw): 0
Conf(NicoHlsOnly): false
Conf(NicoRtmpOnly): false
Conf(NicoFastTs): false
Conf(NicoAutoConvert): false
Conf(NicoForceResv): false
Conf(NicoSkipHb): false
Conf(HttpSkipVerify): false
chdir: /home/ken/livedl
broadcastId not found
Error code: tsarchive
```

Platform: ubuntu 20.04    v2alpha

**Comment by Kotsuha** [comment]
Just encounter same problem today...

**Comment by nnn-revo2012** [comment]
See     https://egg.5ch.net/test/read.cgi/software/1595715643/111-112

**Comment by Kotsuha** [comment]
> From https://egg.5ch.net/test/read.cgi/software/1595715643/111-112
> (Since access to the 5ch forum from overseas may be restricted.)
> Error code: tsarchive appears only when trying to retrieve RTMP stream (not HLS)
> and `broadcastId not found' suggests that a specific patch is not applied.
> See hanaonnao/livedl on GitHub for example and apply the patch.
> 
> Or git clone https://github.com/hanaonnao/livedl.git and build it.
> (All patches created by 5ch volunteer have been applied.)

Thank you! I don't understand how to apply the patch so I choose to build hanaonnao/livedl.git and it's working now. Can you explain a little how to apply the patch? I see that there is patch here:
https://egg.5ch.net/test/read.cgi/software/1570634489/744

Following the link `https://thuploader.orz.hm/uploader/?mode=dl&id=20102` it brings me to a アップローダー site. I don't know what to do next. Seems like I should find the 20102 file but I cannot find it.

**Comment by nnn-revo2012** [comment]
I'm sorry I'm not good at English.

how to apply the patch:
- cd livedl and copy livedl.patch into livedl folder
- patch -p1 <livedl-p20200919.01.patch
See Issue #49 (I can not download videos from timeshift) 

patch etc... See the 5ch forum (Can you see 5ch? Please try to translate.)

https://egg.5ch.net/test/read.cgi/software/1595715643/116-

**Comment by nnn-revo2012** [comment]
I'm sorry I'm not good at English.

I uploaded a program with PullRequests and patches to my Fork.
git clone https://github.com/nnn-revo2012/livedl.git
I recommend using this to make a livedl.

If you want to apply the patch yourself, do the following:
The old patch has disappeared from the uploader. So a new patch was uploaded with all the patches combined.
https://thuploader.orz.hm/miniup/?mode=dl&id=8353

~~~
git clone  https://github.com/himananiito/livedl.git
git checkout master
cd livedl
[Copy the patch to the livedl folder]
patch -p1 <livedl-p20200919.01.patch
go build src/livedl.go
~~~

**Comment by Kennnnnnji** [comment]
@nnn-revo2012 Thanks, I'll try to build `https://github.com/nnn-revo2012/livedl.git`

**Comment by Kotsuha** [comment]
@nnn-revo2012 Thanks! I'll try it later. Your English is probably better than mine :)

**Comment by Kennnnnnji** [comment]
@nnn-revo2012 sorry to be late, but your repo works! thanks a lot.
