### ISSUE TITLE
How to download from YouTube?

### ISSUE THREAD

**Issue by Kotsuha** [himananiito/livedl#58]
Thank you for livedl. I've been using it for a long time. It helps me a lot.

I used to only download from Nico TS. Today I tried to download from YouTube it says:

```
C:\PortableApps (CLI)\livedl
λ livedl -yt LKRCEx1Z0PE
Conf(YtNoStreamlink): false
Conf(YtNoYoutubeDl): false
Conf(HttpSkipVerify): false
Conf(HttpTimeout): 5
chdir: C:\PortableApps (CLI)\livedl
Selen Tatsuki 【NIJISANJI EN】-【PUYO PUYO TETRIS 2】T-spin time【NIJISANJI EN ｜ Selen Tatsuki】_LKRCEx1Z0PE.mp4
[Streamlink for Windows v1.0.0 - Git f7ac894]
comment pos: 00:00:33
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=LKRCEx1Z0PE
[cli][error] Unable to open URL: https://youtube.com/get_video_info (410 Client Error: Gone for url: https://www.youtube.com/get_video_info?video_id=LKRCEx1Z0PE&el=detailpage)

waiting comment
comment pos: 00:07:45
comment pos: 00:15:59
comment pos: 00:23:44
comment pos: 00:32:22
comment pos: 00:44:05
comment pos: 00:57:49
comment pos: 01:11:37
comment pos: 01:21:32
comment pos: 01:30:19
comment pos: 01:34:56
comment pos: 01:39:25
comment pos: 01:52:09
comment pos: 02:02:37
comment pos: 02:10:13
comment pos: 02:12:59
comment pos: 02:16:28
comment pos: 02:20:44

comment done

```

Is the YouTube download feature not working now? Or am I missing something? Thank you.

**Comment by nnn-revo2012** [comment]
Livedl's Youtube download is no longer possible due to changes in youtube specifications several times after December 2020.

If you are using the modified version of Livedl (nnn-revo2012 or hanaonnao), please get the comments and video separately as below.
Comments:
```
$livedl -yt -yt-no-streamlink=on -yt-no-youtube-dl=on LKRCEx1Z0PE
```

Video:
Get yt-dlp and ffmpeg , install it .
```
yt-dlp https://www.youtube.com/watch?v=LKRCEx1Z0PE
```

**Comment by Kotsuha** [comment]
教えてくれてありがとう。I have successfully downloaded the video and comments from YT and used commeon to play them.

**Comment by Kotsuha** [comment]
@nnn-revo2012

I am sorry to bother you again. I use comment because it's strange to open another issue.

Is it possible to use livedl to download the comment of a membership stream archive from YouTube? (I've already know how to download a membership stream archive by yt-dlp)

**Comment by nnn-revo2012** [comment]
>Is it possible to use livedl to download the comment of a membership stream archive from YouTube? (I've already know how to download a membership stream archive by yt-dlp)

It is not possible to download using livedl.

You can download it using jkcommentviewer.
https://twitter.com/nnn_revo2012/status/1656086067945279489

Or add the following options to yt-dlp to download comments in json format,
Convert the comments from json format to XML format using another tool.
```yt-dlp [Other options...] --write-subs  [url]```

**Comment by Kotsuha** [comment]
助けてくれてありがとうございます。
I have successfully download the chat of a member stream by using jkcommentviewer.

> Convert the comments from json format to XML format using another tool.

another tool → Do you mean [comeconv](https://github.com/nnn-revo2012/comeconv)?

**Comment by nnn-revo2012** [comment]
>another tool → Do you mean [comeconv](https://github.com/nnn-revo2012/comeconv)?

Yes, it is.
If you know of another tool that can convert comments from yt-dlp to XML format, you can also use that.
(I don't know of any, so I created comeconv)

**Comment by Kotsuha** [comment]
comeconvも成功しました。とっても便利です。ありがとうございます。

Lastly, an unrelated question.

Do you know if there is a way to play downloaded comments offline, but instead of playing them like Niconico (comments scroll across the screen), they scroll on the side like YouTube? The tools I know so far are [Cometan](http://putin999.web.fc2.com/) and [commeon](http://air.fem.jp/commeon/). They can only play comments like Niconico.

If you know such a tool, please tell me the tool's name. I can search for tutorial myself.

Sorry for a lot of questions. Thank you for your patience.

**Comment by nnn-revo2012** [comment]
>If you know such a tool, please tell me the tool's name. I can search for tutorial myself.

Sorry, I don't know of any such tool.

**Comment by Kotsuha** [comment]
OK Thank you~
